sudo: required

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.21.2

before_install:
  # exit on error
  - set -o errexit
  - set -o pipefail
  
  # Update Docker
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  
  # Pull images to help with cache (allow failure as tag may not exist)
  - set +o errexit
  - docker pull "thebiggerguy/docker-ads-b-dump1090:${TRAVIS_BRANCH}" || true
  - docker pull "thebiggerguy/docker-ads-b-adsbexchange:${TRAVIS_BRANCH}"
  - docker pull "thebiggerguy/docker-ads-b-adsbexchange-mlat:${TRAVIS_BRANCH}"
  - docker pull "thebiggerguy/docker-ads-b-adsbhub:${TRAVIS_BRANCH}"
  - docker pull "thebiggerguy/docker-ads-b-flightradar24:${TRAVIS_BRANCH}"
  - docker pull "thebiggerguy/docker-ads-b-openskynetwork:${TRAVIS_BRANCH}"
  - docker pull "thebiggerguy/docker-ads-b-planefinder:${TRAVIS_BRANCH}"
  - set -o errexit
  
  # setup QEMU
  - docker run --rm --privileged multiarch/qemu-user-static:register

script:
  - TAG="${TRAVIS_BRANCH}"
    docker-compose build
      --build-arg VCS_REF=$(git rev-parse --short HEAD)

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - TAG="${TRAVIS_BRANCH}" docker-compose push